import type { CoupleChallenge } from "@/types/games";

// 35 hand-picked challenges, cycled daily via a deterministic hash. We rotate
// through ALL of them — the more entries, the longer before repeats.
export const COUPLE_CHALLENGES: CoupleChallenge[] = [
	{
		category: "connection",
		description:
			"Atsakykite į 5 klausimus, kurių niekada vienas kitam neuždavėte",
		duration: "20 min.",
		icon: "💬",
		id: "ch-1",
		title: "Nauji klausimai",
	},
	{
		category: "connection",
		description: "Papasakokite 3 prisiminimus, kurių partneris nežino",
		duration: "15 min.",
		icon: "📖",
		id: "ch-2",
		title: "Slapti prisiminimai",
	},
	{
		category: "connection",
		description: "Parašykite laišką sau prieš 10 metų",
		duration: "30 min.",
		icon: "✉️",
		id: "ch-3",
		title: "Laiškas laiku",
	},
	{
		category: "connection",
		description: "Pasidalinkite viena baime, kurios dar niekam nesakėte",
		duration: "20 min.",
		icon: "🌑",
		id: "ch-4",
		title: "Drąsa pasidalinti",
	},
	{
		category: "connection",
		description: "Sudarykite bendrą svajonių sąrašą — 10 punktų",
		duration: "45 min.",
		icon: "✨",
		id: "ch-5",
		title: "Svajonių žemėlapis",
	},
	{
		category: "connection",
		description: "Papasakokite, kuo didžiuojatės vienas kitu",
		duration: "15 min.",
		icon: "🏆",
		id: "ch-6",
		title: "Pasididžiavimas",
	},
	{
		category: "connection",
		description: "Atsakykite, kaip įsivaizduojate save po 20 metų",
		duration: "25 min.",
		icon: "🔮",
		id: "ch-7",
		title: "Ateities vizijos",
	},
	{
		category: "connection",
		description:
			"Pasidalinkite trimis dalykais, kuriuos vertinate partnerystėje",
		duration: "15 min.",
		icon: "💞",
		id: "ch-8",
		title: "Vertybių pokalbis",
	},

	{
		category: "fun",
		description: "Žaiskite stalo žaidimą, kurio nei vienas nesate žaidę",
		duration: "1 val.",
		icon: "🎲",
		id: "ch-9",
		title: "Naujas žaidimas",
	},
	{
		category: "fun",
		description: "Padarykite 10 juokingų nuotraukų vienas kitam",
		duration: "30 min.",
		icon: "🤳",
		id: "ch-10",
		title: "Juokinga fotosesija",
	},
	{
		category: "fun",
		description: "Išmėginkite naują receptą ir įvertinkite rezultatą",
		duration: "1.5 val.",
		icon: "🍳",
		id: "ch-11",
		title: "Kulinarijos eksperimentas",
	},
	{
		category: "fun",
		description: "Sukurkite savo bingo žaidimą ir žaiskite visą vakarą",
		duration: "2 val.",
		icon: "🧩",
		id: "ch-12",
		title: "Namų bingo",
	},
	{
		category: "fun",
		description: "Pieškite vienas kitą iš atminties ir palyginkite",
		duration: "30 min.",
		icon: "🎨",
		id: "ch-13",
		title: "Portretas iš atminties",
	},
	{
		category: "fun",
		description: "Parašykite dainą ar eilėraštį apie jūsų porą",
		duration: "30 min.",
		icon: "🎶",
		id: "ch-14",
		title: "Mūsų daina",
	},
	{
		category: "fun",
		description: "Išbandykite naują kalbą — išmokite 5 frazes",
		duration: "20 min.",
		icon: "🗣️",
		id: "ch-15",
		title: "Nauja kalba",
	},
	{
		category: "fun",
		description: "Surengkite namų karaoke — dainuokite vienas kitam",
		duration: "1 val.",
		icon: "🎤",
		id: "ch-16",
		title: "Karaoke vakaras",
	},

	{
		category: "romantic",
		description: "Paruoškite staigmeną — raštelį, gėlių ar kavos",
		duration: "20 min.",
		icon: "💝",
		id: "ch-17",
		title: "Maža staigmena",
	},
	{
		category: "romantic",
		description: "Lėtas šokis svetainėje prie mėgstamos dainos",
		duration: "10 min.",
		icon: "💃",
		id: "ch-18",
		title: "Šokis poroje",
	},
	{
		category: "romantic",
		description: "Žvakių vakaras — be ekranų, tik pokalbis ir buvimas",
		duration: "2 val.",
		icon: "🕯️",
		id: "ch-19",
		title: "Žvakių vakaras",
	},
	{
		category: "romantic",
		description: "Masažuokite vienas kitą 15 min. su mėgstamu aliejumi",
		duration: "30 min.",
		icon: "💆",
		id: "ch-20",
		title: "Masažas poroje",
	},
	{
		category: "romantic",
		description: "Pašalinkite telefonų naudojimą 3 valandoms",
		duration: "3 val.",
		icon: "📵",
		id: "ch-21",
		title: "Skaitmeninis detoksas",
	},
	{
		category: "romantic",
		description: "Parašykite 5 dalykus, dėl kurių mylite vienas kitą",
		duration: "20 min.",
		icon: "💌",
		id: "ch-22",
		title: "Meilės sąrašas",
	},
	{
		category: "romantic",
		description: "Atkurkite pirmojo pasimatymo scenarijų",
		duration: "1 val.",
		icon: "🥂",
		id: "ch-23",
		title: "Pirmojo susitikimo atkūrimas",
	},
	{
		category: "romantic",
		description: "Padėkite vienas kitam paruošti mėgstamą patiekalą",
		duration: "1 val.",
		icon: "🍷",
		id: "ch-24",
		title: "Vakarienė poroje",
	},

	{
		category: "growth",
		description: "Išmokite naujo įgūdžio kartu — 30 min. praktikos",
		duration: "30 min.",
		icon: "🌱",
		id: "ch-25",
		title: "Naujas įgūdis",
	},
	{
		category: "growth",
		description: "Pasidalinkite knygos ar straipsnio mintimis",
		duration: "20 min.",
		icon: "📚",
		id: "ch-26",
		title: "Knygų klubas",
	},
	{
		category: "growth",
		description: "Sukurkite bendrą tikslą šiam mėnesiui ir žingsnius jam",
		duration: "30 min.",
		icon: "🎯",
		id: "ch-27",
		title: "Bendras tikslas",
	},
	{
		category: "growth",
		description: "Aptarkite vieną neseniai kilusį konfliktą — be kaltinimų",
		duration: "30 min.",
		icon: "🕊️",
		id: "ch-28",
		title: "Sąžiningas pokalbis",
	},
	{
		category: "growth",
		description: "Klausykite mėgstamo podcasto ir aptarkite įspūdžius",
		duration: "1 val.",
		icon: "🎧",
		id: "ch-29",
		title: "Podcast'o diskusijos",
	},
	{
		category: "growth",
		description: "Užsirašykite 3 dalykus, kuriems šiandien dėkojate",
		duration: "10 min.",
		icon: "🙏",
		id: "ch-30",
		title: "Dėkingumo akimirka",
	},

	{
		category: "kindness",
		description: "Padarykite vienas kitam paslaugą be prašymo",
		duration: "20 min.",
		icon: "🤝",
		id: "ch-31",
		title: "Paslauga be žodžių",
	},
	{
		category: "kindness",
		description: "Apskritai apkabinkite vienas kitą bent 30 sekundžių",
		duration: "1 min.",
		icon: "🫂",
		id: "ch-32",
		title: "Ilgas apkabinimas",
	},
	{
		category: "kindness",
		description: "Pasakykite vienas kitam 3 pagarbius komplimentus",
		duration: "5 min.",
		icon: "💐",
		id: "ch-33",
		title: "Trigubas komplimentas",
	},
	{
		category: "kindness",
		description: "Padėkite vienas kitam su kasdiene užduotimi, kuri erzina",
		duration: "30 min.",
		icon: "🧹",
		id: "ch-34",
		title: "Bendras darbas",
	},
	{
		category: "kindness",
		description: "Apsilankykite vietoje, kuri svarbi jūsų partneriui",
		duration: "1 val.",
		icon: "🏞️",
		id: "ch-35",
		title: "Svarbi vieta",
	},
];
