import type { DateIdea } from "@/types/games";

export const DATE_IDEAS: DateIdea[] = [
	// Home
	{
		category: "home",
		duration: "1-2 val.",
		icon: "🍳",
		id: "home-1",
		intensity: "cozy",
		prompt:
			"Pasigaminkite vakarienę kartu — kiekvienas atsako už vieną patiekalą",
	},
	{
		category: "home",
		duration: "2 val.",
		icon: "🎬",
		id: "home-2",
		intensity: "cozy",
		prompt: "Maratono filmų vakaras — išsirinkite 3 filmus, kurių nematėte",
	},
	{
		category: "home",
		duration: "1 val.",
		icon: "🎨",
		id: "home-3",
		intensity: "active",
		prompt: "Tapkite dailininkais — pieškite vienas kitą 10 min.",
	},
	{
		category: "home",
		duration: "30 min.",
		icon: "🛁",
		id: "home-4",
		intensity: "spicy",
		prompt: "Paruoškite vienas kitam atpalaiduojančią vonią su žvakėmis",
	},
	{
		category: "home",
		duration: "1 val.",
		icon: "🧩",
		id: "home-5",
		intensity: "cozy",
		prompt: "Sujunkite 500 dalių dėlionę be kalbėjimo",
	},
	{
		category: "home",
		duration: "1.5 val.",
		icon: "🍕",
		id: "home-6",
		intensity: "active",
		prompt: "Sukurkite picą iš to, ką rasite šaldytuve",
	},
	{
		category: "home",
		duration: "1 val.",
		icon: "📸",
		id: "home-7",
		intensity: "active",
		prompt: "Padarykite 10 juokingų nuotraukų vienas kitam",
	},
	{
		category: "home",
		duration: "30 min.",
		icon: "🎲",
		id: "home-8",
		intensity: "active",
		prompt: "Pasirinkite naują stalo žaidimą ir išmėginkite",
	},
	{
		category: "home",
		duration: "1 val.",
		icon: "📝",
		id: "home-9",
		intensity: "cozy",
		prompt: "Kartu rašykite istoriją — po vieną sakinį",
	},
	{
		category: "home",
		duration: "45 min.",
		icon: "💃",
		id: "home-10",
		intensity: "spicy",
		prompt: "Mėgaukitės lėtu šokiu svetainėje prie žvakių",
	},
	{
		category: "home",
		duration: "2 val.",
		icon: "🍰",
		id: "home-11",
		intensity: "cozy",
		prompt: "Iškepkite kažką saldaus kartu pagal naują receptą",
	},
	{
		category: "home",
		duration: "1 val.",
		icon: "🃏",
		id: "home-12",
		intensity: "cozy",
		prompt: "Surenkite namų karaoke vakarą",
	},

	// Outdoor
	{
		category: "outdoor",
		duration: "2-3 val.",
		icon: "🌳",
		id: "outdoor-1",
		intensity: "active",
		prompt: "Pasivaikščiojimas parke be telefonų — tik jūs",
	},
	{
		category: "outdoor",
		duration: "3-4 val.",
		icon: "🚲",
		id: "outdoor-2",
		intensity: "active",
		prompt: "Dviračių išvyka į vietą, kur dar nesate buvę",
	},
	{
		category: "outdoor",
		duration: "1-2 val.",
		icon: "🏛️",
		id: "outdoor-3",
		intensity: "cozy",
		prompt: "Aplankykite muziejų ar galeriją",
	},
	{
		category: "outdoor",
		duration: "2 val.",
		icon: "🌅",
		id: "outdoor-4",
		intensity: "cozy",
		prompt: "Pasitikite saulėlydį ar saulėtekį kartu",
	},
	{
		category: "outdoor",
		duration: "1 val.",
		icon: "📸",
		id: "outdoor-5",
		intensity: "cozy",
		prompt: "Padarykite fotosesiją mieste — keistose vietose",
	},
	{
		category: "outdoor",
		duration: "2-3 val.",
		icon: "🥾",
		id: "outdoor-6",
		intensity: "active",
		prompt: "Pasivaikščiokite nauju pėsčiųjų taku",
	},
	{
		category: "outdoor",
		duration: "2 val.",
		icon: "🐶",
		id: "outdoor-7",
		intensity: "active",
		prompt: "Pasivaikščiokite prie gyvūnų prieglaudos — paglostykite šunis",
	},
	{
		category: "outdoor",
		duration: "1 val.",
		icon: "⛸️",
		id: "outdoor-8",
		intensity: "active",
		prompt: "Pačiūžkite ledo arba riedučiais",
	},
	{
		category: "outdoor",
		duration: "3 val.",
		icon: "🛶",
		id: "outdoor-9",
		intensity: "active",
		prompt: "Išbandykite baidares ar valtelę ežere",
	},
	{
		category: "outdoor",
		duration: "1-2 val.",
		icon: "🌸",
		id: "outdoor-10",
		intensity: "cozy",
		prompt: "Suraskite žydinčių augalų parką ir pasivaikščiokite",
	},

	// Food
	{
		category: "food",
		duration: "2 val.",
		icon: "🍽️",
		id: "food-1",
		intensity: "cozy",
		prompt: "Išbandykite restoraną su virtuve, kurios dar neragavote",
	},
	{
		category: "food",
		duration: "3-4 val.",
		icon: "🍷",
		id: "food-2",
		intensity: "spicy",
		prompt: "Vyno ar kokteilių degustacija namuose — 3 skirtingi gėrimai",
	},
	{
		category: "food",
		duration: "2 val.",
		icon: "🌮",
		id: "food-3",
		intensity: "cozy",
		prompt: "Pasirinkite atsitiktinį restoraną — nei vienas nematėte meniu",
	},
	{
		category: "food",
		duration: "1 val.",
		icon: "☕",
		id: "food-4",
		intensity: "cozy",
		prompt:
			"Apsilankykite naujoje kavinėje ir užsakykite tai, ko niekada neragavote",
	},
	{
		category: "food",
		duration: "1.5 val.",
		icon: "🥐",
		id: "food-5",
		intensity: "cozy",
		prompt: "Pusryčiai lovoje — patiekite vienas kitam",
	},
	{
		category: "food",
		duration: "2 val.",
		icon: "🍣",
		id: "food-6",
		intensity: "cozy",
		prompt: "Sukurkite suši ar suktinukus namuose",
	},
	{
		category: "food",
		duration: "1 val.",
		icon: "🧁",
		id: "food-7",
		intensity: "cozy",
		prompt: "Išsikepkite cupcakes ir papuoškite kartu",
	},
	{
		category: "food",
		duration: "2 val.",
		icon: "🍝",
		id: "food-8",
		intensity: "cozy",
		prompt: "Kartu pagaminkite itališką vakarienę — nuo užkandžio iki deserto",
	},

	// Romantic
	{
		category: "romantic",
		duration: "1 val.",
		icon: "💌",
		id: "romantic-1",
		intensity: "spicy",
		prompt: "Rašykite vienas kitam meilės laiškus — perskaitysite vakare",
	},
	{
		category: "romantic",
		duration: "30 min.",
		icon: "💆",
		id: "romantic-2",
		intensity: "spicy",
		prompt: "Masažuokite vienas kitą 15 min. su mėgstamais aliejais",
	},
	{
		category: "romantic",
		duration: "1 val.",
		icon: "✨",
		id: "romantic-3",
		intensity: "spicy",
		prompt: "Pasiruoškite romantišką vakarą — tik žvakės ir muzika",
	},
	{
		category: "romantic",
		duration: "20 min.",
		icon: "🌹",
		id: "romantic-4",
		intensity: "spicy",
		prompt: "Papasakokite 5 dalykus, kuriuos dievinate viename kitame",
	},
	{
		category: "romantic",
		duration: "1 val.",
		icon: "📖",
		id: "romantic-5",
		intensity: "cozy",
		prompt: "Skaitykite vienas kitam eilėraščius ar knygos skyrių",
	},
	{
		category: "romantic",
		duration: "2 val.",
		icon: "🕯️",
		id: "romantic-6",
		intensity: "spicy",
		prompt: "Sensorinis vakaras: aklai paragaukite maisto ir atspėkite",
	},
	{
		category: "romantic",
		duration: "30 min.",
		icon: "💋",
		id: "romantic-7",
		intensity: "spicy",
		prompt: "Atkurkite pirmąjį jūsų pasimatymą",
	},
	{
		category: "romantic",
		duration: "1 val.",
		icon: "🎶",
		id: "romantic-8",
		intensity: "spicy",
		prompt: "Kurkite abiem žinomą dainų grojaraštį — tik jūsų dainos",
	},

	// Fun
	{
		category: "fun",
		duration: "2 val.",
		icon: "🎳",
		id: "fun-1",
		intensity: "active",
		prompt: "Boulingo vakaras — pralošėjas pildo norą",
	},
	{
		category: "fun",
		duration: "1.5 val.",
		icon: "🕵️",
		id: "fun-2",
		intensity: "active",
		prompt: "Išbandykite escape room mieste",
	},
	{
		category: "fun",
		duration: "2 val.",
		icon: "🎨",
		id: "fun-3",
		intensity: "cozy",
		prompt: "Tapybos ir vyno vakaras — dažykite viens kitą",
	},
	{
		category: "fun",
		duration: "1 val.",
		icon: "🎤",
		id: "fun-4",
		intensity: "cozy",
		prompt: "Karaoke — išsirinkite dainą, kurios niekada nedainavote",
	},
	{
		category: "fun",
		duration: "2 val.",
		icon: "🃏",
		id: "fun-5",
		intensity: "cozy",
		prompt: "Stalo žaidimų turnyras — kas laimi 3 partijas",
	},
	{
		category: "fun",
		duration: "1 val.",
		icon: "🎯",
		id: "fun-6",
		intensity: "active",
		prompt: "Smiginio ar boulingo treniruotė namuose",
	},
	{
		category: "fun",
		duration: "3 val.",
		icon: "🎢",
		id: "fun-7",
		intensity: "active",
		prompt: "Atrakcionų parkas — išbandykite visus kalnelius",
	},
	{
		category: "fun",
		duration: "2 val.",
		icon: "🧗",
		id: "fun-8",
		intensity: "active",
		prompt: "Kopimas uolomis arba virvių parke",
	},
];
