import type { ThisOrThatPair } from "@/types/games";

// "This or That" couples edition — both partners swipe independently, then
// reveal whether they matched. Pairs are localizable-friendly (text only).
export const THIS_OR_THAT_PAIRS: ThisOrThatPair[] = [
	{ a: "Paplūdimys", b: "Kalnai", iconA: "🏖️", iconB: "🏔️", id: "tot-1" },
	{ a: "Kava", b: "Arbata", iconA: "☕", iconB: "🍵", id: "tot-2" },
	{ a: "Saulėtekis", b: "Saulėlydis", iconA: "🌅", iconB: "🌇", id: "tot-3" },
	{
		a: "Vakarienė namie",
		b: "Vakarienė restorane",
		iconA: "🏠",
		iconB: "🍽️",
		id: "tot-4",
	},
	{
		a: "Atsiriboti nuo technologijų",
		b: "Žaisti žaidimus kartu",
		iconA: "📵",
		iconB: "🎮",
		id: "tot-5",
	},
	{
		a: "Romantinė komedija",
		b: "Siaubo filmas",
		iconA: "💕",
		iconB: "👻",
		id: "tot-6",
	},
	{ a: "Pica", b: "Sushi", iconA: "🍕", iconB: "🍣", id: "tot-7" },
	{ a: "Vasara", b: "Žiema", iconA: "☀️", iconB: "❄️", id: "tot-8" },
	{
		a: "Sportas namie",
		b: "Sportas lauke",
		iconA: "🏋️",
		iconB: "🏃",
		id: "tot-9",
	},
	{
		a: "Ilgas atostogas",
		b: "Trumpos savaitgalio išvykos",
		iconA: "🗓️",
		iconB: "🚗",
		id: "tot-10",
	},
	{ a: "Glaustytis", b: "Būti lauke", iconA: "🤗", iconB: "🌳", id: "tot-11" },
	{
		a: "Groti gitara",
		b: "Groti būgnais",
		iconA: "🎸",
		iconB: "🥁",
		id: "tot-12",
	},
	{
		a: "Skaityti knygą",
		b: "Žiūrėti serialą",
		iconA: "📚",
		iconB: "📺",
		id: "tot-13",
	},
	{ a: "Mieste", b: "Kaime", iconA: "🏙️", iconB: "🌾", id: "tot-14" },
	{
		a: "Vėlyvi pusryčiai",
		b: "Ankstyva vakarienė",
		iconA: "🥞",
		iconB: "🍲",
		id: "tot-15",
	},
	{ a: "Katė", b: "Šuo", iconA: "🐱", iconB: "🐶", id: "tot-16" },
	{
		a: "Tylus vakaras",
		b: "Triukšmingas vakarėlis",
		iconA: "🤫",
		iconB: "🎉",
		id: "tot-17",
	},
	{ a: "Šokoladas", b: "Vaisiai", iconA: "🍫", iconB: "🍓", id: "tot-18" },
	{ a: "Muziejus", b: "Koncentras", iconA: "🖼️", iconB: "🎶", id: "tot-19" },
	{
		a: "Kelionė lėktuvu",
		b: "Kelionė automobiliu",
		iconA: "✈️",
		iconB: "🚙",
		id: "tot-20",
	},
	{ a: "Spa", b: "Aktyvi pramoga", iconA: "🧖", iconB: "🏄", id: "tot-21" },
	{
		a: 'Pasakyti "aš tave myliu"',
		b: "Parodyti gestais",
		iconA: "💬",
		iconB: "🤲",
		id: "tot-22",
	},
	{
		a: "Stalo žaidimai",
		b: "Kompiuteriniai žaidimai",
		iconA: "🎲",
		iconB: "🕹️",
		id: "tot-23",
	},
	{
		a: "Pagrindinis patiekalas",
		b: "Desertas",
		iconA: "🥘",
		iconB: "🍰",
		id: "tot-24",
	},
	{
		a: "Ryto žmogus",
		b: "Nakties žmogus",
		iconA: "🌞",
		iconB: "🌙",
		id: "tot-25",
	},
	{ a: "Plaukti", b: "Bėgioti", iconA: "🏊", iconB: "🏃", id: "tot-26" },
	{
		a: "Klasikinė muzika",
		b: "Roko muzika",
		iconA: "🎻",
		iconB: "🎸",
		id: "tot-27",
	},
	{
		a: "Stipri kava",
		b: "Lengva latte",
		iconA: "☕",
		iconB: "🥛",
		id: "tot-28",
	},
	{
		a: "Valgyti kartu prie stalo",
		b: "Ant sofos su filmu",
		iconA: "🍴",
		iconB: "🛋️",
		id: "tot-29",
	},
	{
		a: "Drąsus romanas",
		b: "Švelni meilės istorija",
		iconA: "📕",
		iconB: "💗",
		id: "tot-30",
	},
];
