services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: santykiuklausimai
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
