import type { SpicyCard } from "@/types/spicyCards";

export const SPICY_CARDS: SpicyCard[] = [
	// Kiss cards
	{
		color: "#FF6B9D",
		description: "Pabučiuok partnerį/-ę į lūpas",
		icon: "💋",
		id: "kiss-1",
		title: "Bučinys",
		type: "kiss",
	},
	{
		color: "#FF6B9D",
		description: "Švelniai pabučiuok partnerio/-ės kaktą",
		icon: "💋",
		id: "kiss-2",
		title: "Švelnumas",
		type: "kiss",
	},
	{
		color: "#FF6B9D",
		description: "Pabučiuok partnerį/-ę į pasirinktą vietą",
		icon: "💋",
		id: "kiss-3",
		title: "Netikėtumas",
		type: "kiss",
	},

	// Challenge cards
	{
		color: "#FFA500",
		description: "Pašok lėtą šokį 30 sekundžių be muzikos",
		icon: "🎯",
		id: "challenge-1",
		title: "Šokių pamoka",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Padainuok meilės dainą partneriui",
		icon: "🎯",
		id: "challenge-2",
		title: "Dainavimas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Pašok 20 kartų kartu laikydami rankas",
		icon: "🎯",
		id: "challenge-3",
		title: "Šuoliai",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Juokis kuo garsiau 20 sekundžių",
		icon: "🎯",
		id: "challenge-4",
		title: "Juoko konkursas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Padaryk 10 atsispaudimų, partneris skaičiuoja",
		icon: "🎯",
		id: "challenge-5",
		title: "Atsispaudimai",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Pasuk ratu 10 kartų ir pabandyk pabučiuoti partnerį",
		icon: "🎯",
		id: "challenge-6",
		title: "Sukimasis",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Pamėgdžiok garsų gyvūną, partneris turi atspėti",
		icon: "🎯",
		id: "challenge-7",
		title: "Pamėgdžiojimas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šok kaip beprotis 30 sekundžių",
		icon: "🎯",
		id: "challenge-8",
		title: "Beprotiškas šokis",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Plok ritmingai 30 sekundžių kartu",
		icon: "🎯",
		id: "challenge-9",
		title: "Plojimas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šokinėk ant vienos kojos 15 kartų",
		icon: "🎯",
		id: "challenge-10",
		title: "Šuoliukai",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Daryk juokingus garsus 20 sekundžių",
		icon: "🎯",
		id: "challenge-11",
		title: "Garsas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Bėk vietoje 30 sekundžių kartu",
		icon: "🎯",
		id: "challenge-12",
		title: "Bėgimas vietoje",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Dainuok kaip operoje kuo garsiau",
		icon: "🎯",
		id: "challenge-13",
		title: "Dainuok garsiai",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Mojuok rankomis kaip paukštis 20 sekundžių",
		icon: "🎯",
		id: "challenge-14",
		title: "Mojuok rankomis",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Padaryk 15 pritūpimų kartu",
		icon: "🎯",
		id: "challenge-15",
		title: "Pritūpimai",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Imituok plaukimą 20 sekundžių",
		icon: "🎯",
		id: "challenge-16",
		title: "Plaukimas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šok kaip rockžvaigždė 30 sekundžių",
		icon: "🎯",
		id: "challenge-17",
		title: "Šėlsmas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Padainuok giesme partneriui",
		icon: "🎯",
		id: "challenge-18",
		title: "Giesmė",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šokinėk aukštyn žemyn 30 kartų",
		icon: "🎯",
		id: "challenge-19",
		title: "Šokinėjimas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Juokis kaip beprotis ir užkrėsk partnerį",
		icon: "🎯",
		id: "challenge-20",
		title: "Juoko sprogimas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Pašok baletą 15 sekundžių",
		icon: "🎯",
		id: "challenge-21",
		title: "Baleto šuolis",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: 'Rėk "Myliu tave!" kuo garsiau',
		icon: "🎯",
		id: "challenge-22",
		title: "Rėkimas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šokite kartu lėtą šokį ir sukitės",
		icon: "🎯",
		id: "challenge-23",
		title: "Šokis kartu",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šok hip hop 20 sekundžių",
		icon: "🎯",
		id: "challenge-24",
		title: "Hip hop",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Plok sau per šonus kaip gorila",
		icon: "🎯",
		id: "challenge-25",
		title: "Plojimas kūnui",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Trepsėk kojomis 30 sekundžių",
		icon: "🎯",
		id: "challenge-26",
		title: "Trepsėjimas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Dainuok 3 skirtingas dainas po 10 sekundžių",
		icon: "🎯",
		id: "challenge-27",
		title: "Dainuok daug",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Boksuok orą 30 sekundžių",
		icon: "🎯",
		id: "challenge-28",
		title: "Boksas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šokite salsa šokį kartu",
		icon: "🎯",
		id: "challenge-29",
		title: "Salsa šokis",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Daryk keistus judesius 30 sekundžių",
		icon: "🎯",
		id: "challenge-30",
		title: "Judesiai",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Padainuok operinį arią",
		icon: "🎯",
		id: "challenge-31",
		title: "Dainuok operą",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šok ant vienos kojos 20 sekundžių",
		icon: "🎯",
		id: "challenge-32",
		title: "Šokis ant vienos",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Kas ilgiau išlaiko juoką be sustojimo",
		icon: "🎯",
		id: "challenge-33",
		title: "Juoko varžybos",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šok ir plok viršuje 15 kartų",
		icon: "🎯",
		id: "challenge-34",
		title: "Šuoliai su plojimais",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šokite tango 20 sekundžių",
		icon: "🎯",
		id: "challenge-35",
		title: "Tango",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Laikyk planką 20 sekundžių",
		icon: "🎯",
		id: "challenge-36",
		title: "Plankas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Padainuok greitą dainą kuo greičiau",
		icon: "🎯",
		id: "challenge-37",
		title: "Dainuok greitai",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šokinėk kaip triušis 20 sekundžių",
		icon: "🎯",
		id: "challenge-38",
		title: "Šokinėk kaip triušis",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Vaikščiok kaip pingvinas po kambarį",
		icon: "🎯",
		id: "challenge-39",
		title: "Vaikščiok juokingai",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šok breakdance judesį",
		icon: "🎯",
		id: "challenge-40",
		title: "Breakdance",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Padainuok labai tyliai į partnerio ausį",
		icon: "🎯",
		id: "challenge-41",
		title: "Dainuok tyliai",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šok ir sukis 20 sekundžių",
		icon: "🎯",
		id: "challenge-42",
		title: "Šokis su sukimais",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Užšok ant partneriui 3 kartus",
		icon: "🎯",
		id: "challenge-43",
		title: "Užšokimas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Padainuok rap dainą",
		icon: "🎯",
		id: "challenge-44",
		title: "Dainuok rap",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Imituok slidinėjimą 20 sekundžių",
		icon: "🎯",
		id: "challenge-45",
		title: "Slidinėjimas",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šok kaip turi begalinę energiją",
		icon: "🎯",
		id: "challenge-46",
		title: "Energingas šokis",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šok disco šokį su įspūdingais judesiais",
		icon: "🎯",
		id: "challenge-47",
		title: "Disko šokis",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Padaryk 5 burpius",
		icon: "🎯",
		id: "challenge-48",
		title: "Burpiai",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Šok kaip robotas 30 sekundžių",
		icon: "🎯",
		id: "challenge-49",
		title: "Šok robotą",
		type: "challenge",
	},
	{
		color: "#FFA500",
		description: "Prajuokinki partnerį bet kokiu būdu",
		icon: "🎯",
		id: "challenge-50",
		title: "Juoko akimirkos",
		type: "challenge",
	},

	// Compliment cards
	{
		color: "#C77DFF",
		description: "Pasakyk, kas tau labiausiai patinka partneryje fiziškai",
		icon: "💝",
		id: "compliment-1",
		title: "Komplimentas",
		type: "compliment",
	},
	{
		color: "#C77DFF",
		description: "Pasakyk, kokia partnero savybė tave labiausiai traukia",
		icon: "💝",
		id: "compliment-2",
		title: "Gražūs žodžiai",
		type: "compliment",
	},
	{
		color: "#C77DFF",
		description: "Pasakyk, už ką esi labiausiai dėkingas/-a partneriui",
		icon: "💝",
		id: "compliment-3",
		title: "Vertinimas",
		type: "compliment",
	},

	// Massage cards
	{
		color: "#7B68EE",
		description: "Padaryk 2 minučių pečių masažą partneriui",
		icon: "💆",
		id: "massage-1",
		title: "Masažas",
		type: "massage",
	},
	{
		color: "#7B68EE",
		description: "Švelniai pamasažuok partnero galvą",
		icon: "💆",
		id: "massage-2",
		title: "Atsipalaidavimas",
		type: "massage",
	},
	{
		color: "#7B68EE",
		description: "Pamasažuok partneriui kojas 3 minutes",
		icon: "💆",
		id: "massage-3",
		title: "Rūpestis",
		type: "massage",
	},

	// Slap cards (playful)
	{
		color: "#FF6347",
		description: "Lengvai plokštelėk partnerį/-ę už kvailiojimą",
		icon: "👋",
		id: "slap-1",
		title: "Žaismingas",
		type: "slap",
	},
	{
		color: "#FF6347",
		description: "Žaismingai nubauski partnerį už paskutinį pralaimėjimą",
		icon: "👋",
		id: "slap-2",
		title: "Bausmė",
		type: "slap",
	},

	// Whisper cards
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu mane sujaudini"',
		icon: "🤫",
		id: "whisper-1",
		title: "Šnibždesys",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Noriu būti arčiau tavęs"',
		icon: "🤫",
		id: "whisper-2",
		title: "Paslaptis",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Galvoju apie tave visą dieną"',
		icon: "🤫",
		id: "whisper-3",
		title: "Gundymas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu man labai patinki"',
		icon: "🤫",
		id: "whisper-4",
		title: "Troškimas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tavo kvapas mane vilioja"',
		icon: "🤫",
		id: "whisper-5",
		title: "Švelnumas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Kas būtų, jei likime vieni?"',
		icon: "🤫",
		id: "whisper-6",
		title: "Intriga",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Norėčiau pabučiuoti tave čia ir dabar"',
		icon: "🤫",
		id: "whisper-7",
		title: "Drąsa",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Man patinka, kaip tu į mane žiūri"',
		icon: "🤫",
		id: "whisper-8",
		title: "Aistra",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Negaliu nustoti apie tave galvojęs"',
		icon: "🤫",
		id: "whisper-9",
		title: "Geismas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu mane išvedai iš proto"',
		icon: "🤫",
		id: "whisper-10",
		title: "Pagunda",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Turiu fantaziją apie mus du"',
		icon: "🤫",
		id: "whisper-11",
		title: "Fantazija",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Noriu pajusti tavo lietimą"',
		icon: "🤫",
		id: "whisper-12",
		title: "Troškimas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Man patinka tavo rankos ant manęs"',
		icon: "🤫",
		id: "whisper-13",
		title: "Aistra",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Sapnavau apie tave naktį"',
		icon: "🤫",
		id: "whisper-14",
		title: "Svajonė",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu esi toks seksualus šiandien"',
		icon: "🤫",
		id: "whisper-15",
		title: "Geidulingumas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Norėčiau pasilikti su tavimi šią naktį"',
		icon: "🤫",
		id: "whisper-16",
		title: "Noras",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Galvoju ką darytume, jei būtume vieni"',
		icon: "🤫",
		id: "whisper-17",
		title: "Užuomina",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Pasiilgau tavo bučinių"',
		icon: "🤫",
		id: "whisper-18",
		title: "Pasiilgimas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu man sukeli šiurpuliukus"',
		icon: "🤫",
		id: "whisper-19",
		title: "Troškimas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Norėčiau tyrinėti tavo kūną"',
		icon: "🤫",
		id: "whisper-20",
		title: "Vilionė",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Man patinka, kaip tu mane lieti"',
		icon: "🤫",
		id: "whisper-21",
		title: "Intymumas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu mane sužavėjai"',
		icon: "🤫",
		id: "whisper-22",
		title: "Jausmingumas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tavo lūpos atrodo tokios minkštos"',
		icon: "🤫",
		id: "whisper-23",
		title: "Pagunda",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Galvoju apie tave duše"',
		icon: "🤫",
		id: "whisper-24",
		title: "Drąsa",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Noriu išsiaiškinti, kas tau patinka"',
		icon: "🤫",
		id: "whisper-25",
		title: "Geismas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu esi nepakartojamas"',
		icon: "🤫",
		id: "whisper-26",
		title: "Aistra",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description:
			'Sušnibžděk: "Norėčiau pamiršti visus aplink ir bučiuoti tik tave"',
		icon: "🤫",
		id: "whisper-27",
		title: "Troškimas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Man patinka, kai tu šypsaisi"',
		icon: "🤫",
		id: "whisper-28",
		title: "Gundymas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu man visiškai įsirėžei į mintis"',
		icon: "🤫",
		id: "whisper-29",
		title: "Noras",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Man patinka tavo balsas"',
		icon: "🤫",
		id: "whisper-30",
		title: "Vilionė",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Vakar galvojau apie mus lovoje"',
		icon: "🤫",
		id: "whisper-31",
		title: "Fantazija",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Norėčiau pabūti su tavimi vienatvėje"',
		icon: "🤫",
		id: "whisper-32",
		title: "Aistra",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu man patinki labiau nei turėtum"',
		icon: "🤫",
		id: "whisper-33",
		title: "Pagunda",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Kai tu šalia, jaučiuosi kitaip"',
		icon: "🤫",
		id: "whisper-34",
		title: "Jausmingumas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Man sunku susivaldyti šalia tavęs"',
		icon: "🤫",
		id: "whisper-35",
		title: "Troškimas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu žinai, kaip mane sujaudinti"',
		icon: "🤫",
		id: "whisper-36",
		title: "Gundymas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Norėčiau su tavimi išbandyti ką nors naujo"',
		icon: "🤫",
		id: "whisper-37",
		title: "Drąsa",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Man patinka, kai mes liečiamės"',
		icon: "🤫",
		id: "whisper-38",
		title: "Geismas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tavo akys mane hipnotizuoja"',
		icon: "🤫",
		id: "whisper-39",
		title: "Vilionė",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Norėčiau būti arčiau tavęs dabar"',
		icon: "🤫",
		id: "whisper-40",
		title: "Aistra",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu esi viskas, ko man reikia"',
		icon: "🤫",
		id: "whisper-41",
		title: "Noras",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Turiu planą šiai nakčiai"',
		icon: "🤫",
		id: "whisper-42",
		title: "Fantazija",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Man patinka tavo kūno forma"',
		icon: "🤫",
		id: "whisper-43",
		title: "Pagunda",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Negaliu atitraukti nuo tavęs akių"',
		icon: "🤫",
		id: "whisper-44",
		title: "Troškimas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu manęs nepaleidai iš galvos"',
		icon: "🤫",
		id: "whisper-45",
		title: "Gundymas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Man patinka būti su tavimi"',
		icon: "🤫",
		id: "whisper-46",
		title: "Jausmingumas",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu mane įkvepi"',
		icon: "🤫",
		id: "whisper-47",
		title: "Aistra",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Man labai patinka tavo šypsena"',
		icon: "🤫",
		id: "whisper-48",
		title: "Vilionė",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Kai tu šalia, pasaulis tampa geresnis"',
		icon: "🤫",
		id: "whisper-49",
		title: "Drąsa",
		type: "whisper",
	},
	{
		color: "#FF1493",
		description: 'Sušnibžděk: "Tu esi vienintelis, kurio noriu"',
		icon: "🤫",
		id: "whisper-50",
		title: "Geismas",
		type: "whisper",
	},

	// Dare cards
	{
		color: "#FF4500",
		description: "Išdrįsk pasakyti ką nors, ko niekada nesakei",
		icon: "🔥",
		id: "dare-1",
		title: "Išdrįsk",
		type: "dare",
	},
	{
		color: "#FF4500",
		description: "Padaryk kažką spontaniško",
		icon: "🔥",
		id: "dare-2",
		title: "Drąsa",
		type: "dare",
	},
	{
		color: "#FF4500",
		description: "Papasakok apie savo fantaziją",
		icon: "🔥",
		id: "dare-3",
		title: "Rizika",
		type: "dare",
	},

	// Truth cards
	{
		color: "#4169E1",
		description: "Atsakyk į bet kokį partnero klausimą sąžiningai",
		icon: "💭",
		id: "truth-1",
		title: "Tiesa",
		type: "truth",
	},
	{
		color: "#4169E1",
		description: "Papasakok kažką, ko partneris dar nežino",
		icon: "💭",
		id: "truth-2",
		title: "Atvirumas",
		type: "truth",
	},

	// Hug cards
	{
		color: "#FFB6C1",
		description: "Apkabink partnerį/-ę 30 sekundžių tyloje",
		icon: "🤗",
		id: "hug-1",
		title: "Apkabinimas",
		type: "hug",
	},
	{
		color: "#FFB6C1",
		description: "Stipriai apkabink partnerį/-ę",
		icon: "🤗",
		id: "hug-2",
		title: "Šiluma",
		type: "hug",
	},

	// Dance cards
	{
		color: "#DA70D6",
		description: "Pašokite lėtą šokį be muzikos",
		icon: "💃",
		id: "dance-1",
		title: "Šokis",
		type: "dance",
	},
	{
		color: "#DA70D6",
		description: "Šokite kartu vieną minutę",
		icon: "💃",
		id: "dance-2",
		title: "Judesys",
		type: "dance",
	},
];

export const DEFAULT_SPICY_SETTINGS = {
	enabled: true,
	enabledTypes: [
		"kiss",
		"challenge",
		"compliment",
		"massage",
		"slap",
		"whisper",
		"dare",
		"truth",
		"hug",
		"dance",
	] as const,
	rarity: "medium" as const, // 30% chance
};

export const RARITY_LABELS = {
	frequent: "🟡 Dažnas (40%)",
	medium: "⚪ Vidutinis (30%)",
	rare: "🔹 Retas (5%)",
	"semi-rare": "🔸 Pusiau retas (15%)",
	ultra: "🔥 Ultra dažnas (50%)",
};

export const SPICY_CARD_TYPE_LABELS = {
	challenge: "Iššūkis 🎯",
	compliment: "Komplimentas 💝",
	dance: "Šokis 💃",
	dare: "Išdrįsk 🔥",
	hug: "Apkabinimas 🤗",
	kiss: "Bučinys 💋",
	massage: "Masažas 💆",
	slap: "Žaismingas 👋",
	truth: "Tiesa 💭",
	whisper: "Šnibždesys 🤫",
};
