import { SpicyCard } from '@/types/spicyCards';

export const SPICY_CARDS: SpicyCard[] = [
  // Kiss cards
  {
    id: 'kiss-1',
    type: 'kiss',
    title: 'Bučinys',
    description: 'Pabučiuok partnerį/-ę į lūpas',
    icon: '💋',
    color: '#FF6B9D',
  },
  {
    id: 'kiss-2',
    type: 'kiss',
    title: 'Švelnumas',
    description: 'Švelniai pabučiuok partnerio/-ės kaktą',
    icon: '💋',
    color: '#FF6B9D',
  },
  {
    id: 'kiss-3',
    type: 'kiss',
    title: 'Netikėtumas',
    description: 'Pabučiuok partnerį/-ę į pasirinktą vietą',
    icon: '💋',
    color: '#FF6B9D',
  },

  // Challenge cards
  {
    id: 'challenge-1',
    type: 'challenge',
    title: 'Iššūkis',
    description: 'Papasakok 3 dalykus, kuriuos mėgsti partneryje per 30 sekundžių',
    icon: '🎯',
    color: '#FFA500',
  },
  {
    id: 'challenge-2',
    type: 'challenge',
    title: 'Žaidimas',
    description: 'Pažvelk į partnerio akis 60 sekundžių be juoko',
    icon: '🎯',
    color: '#FFA500',
  },
  {
    id: 'challenge-3',
    type: 'challenge',
    title: 'Drąsa',
    description: 'Padaryk kažką, ko niekada nedrįsai prašyti',
    icon: '🎯',
    color: '#FFA500',
  },

  // Compliment cards
  {
    id: 'compliment-1',
    type: 'compliment',
    title: 'Komplimentas',
    description: 'Pasakyk, kas tau labiausiai patinka partneryje fiziškai',
    icon: '💝',
    color: '#C77DFF',
  },
  {
    id: 'compliment-2',
    type: 'compliment',
    title: 'Gražūs žodžiai',
    description: 'Pasakyk, kokia partnero savybė tave labiausiai traukia',
    icon: '💝',
    color: '#C77DFF',
  },
  {
    id: 'compliment-3',
    type: 'compliment',
    title: 'Vertinimas',
    description: 'Pasakyk, už ką esi labiausiai dėkingas/-a partneriui',
    icon: '💝',
    color: '#C77DFF',
  },

  // Massage cards
  {
    id: 'massage-1',
    type: 'massage',
    title: 'Masažas',
    description: 'Padaryk 2 minučių pečių masažą partneriui',
    icon: '💆',
    color: '#7B68EE',
  },
  {
    id: 'massage-2',
    type: 'massage',
    title: 'Atsipalaidavimas',
    description: 'Švelniai pamasažuok partnero galvą',
    icon: '💆',
    color: '#7B68EE',
  },
  {
    id: 'massage-3',
    type: 'massage',
    title: 'Rūpestis',
    description: 'Pamasažuok partneriui kojas 3 minutes',
    icon: '💆',
    color: '#7B68EE',
  },

  // Slap cards (playful)
  {
    id: 'slap-1',
    type: 'slap',
    title: 'Žaismingas',
    description: 'Lengvai plokštelėk partnerį/-ę už kvailiojimą',
    icon: '👋',
    color: '#FF6347',
  },
  {
    id: 'slap-2',
    type: 'slap',
    title: 'Bausmė',
    description: 'Žaismingai nubauski partnerį už paskutinį pralaimėjimą',
    icon: '👋',
    color: '#FF6347',
  },

  // Whisper cards
  {
    id: 'whisper-1',
    type: 'whisper',
    title: 'Šnibždesys',
    description: 'Sušnibžděk: "Tu mane sujaudini"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-2',
    type: 'whisper',
    title: 'Paslaptis',
    description: 'Sušnibžděk: "Noriu būti arčiau tavęs"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-3',
    type: 'whisper',
    title: 'Gundymas',
    description: 'Sušnibžděk: "Galvoju apie tave visą dieną"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-4',
    type: 'whisper',
    title: 'Troškimas',
    description: 'Sušnibžděk: "Tu man labai patinki"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-5',
    type: 'whisper',
    title: 'Švelnumas',
    description: 'Sušnibžděk: "Tavo kvapas mane vilioja"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-6',
    type: 'whisper',
    title: 'Intriga',
    description: 'Sušnibžděk: "Kas būtų, jei likime vieni?"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-7',
    type: 'whisper',
    title: 'Drąsa',
    description: 'Sušnibžděk: "Norėčiau pabučiuoti tave čia ir dabar"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-8',
    type: 'whisper',
    title: 'Aistра',
    description: 'Sušnibžděk: "Man patinka, kaip tu į mane žiūri"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-9',
    type: 'whisper',
    title: 'Geismas',
    description: 'Sušnibžděk: "Negaliu nustoti apie tave galvojęs"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-10',
    type: 'whisper',
    title: 'Pagunda',
    description: 'Sušnibžděk: "Tu mane išvedai iš proto"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-11',
    type: 'whisper',
    title: 'Fantazija',
    description: 'Sušnibžděk: "Turiu fantaziją apie mus du"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-12',
    type: 'whisper',
    title: 'Troškimas',
    description: 'Sušnibžděk: "Noriu pajusti tavo lietimą"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-13',
    type: 'whisper',
    title: 'Aistra',
    description: 'Sušnibžděk: "Man patinka tavo rankos ant manęs"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-14',
    type: 'whisper',
    title: 'Svajonė',
    description: 'Sušnibžděk: "Sapnavau apie tave naktį"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-15',
    type: 'whisper',
    title: 'Geidulingumas',
    description: 'Sušnibžděk: "Tu esi toks seksualus šiandien"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-16',
    type: 'whisper',
    title: 'Noras',
    description: 'Sušnibžděk: "Norėčiau pasilikti su tavimi šią naktį"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-17',
    type: 'whisper',
    title: 'Užuomina',
    description: 'Sušnibžděk: "Galvoju ką darytume, jei būtume vieni"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-18',
    type: 'whisper',
    title: 'Pasiilgimas',
    description: 'Sušnibžděk: "Pasiilgau tavo bučinių"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-19',
    type: 'whisper',
    title: 'Troškimas',
    description: 'Sušnibžděk: "Tu man sukeli šiurpuliukus"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-20',
    type: 'whisper',
    title: 'Vilionė',
    description: 'Sušnibžděk: "Norėčiau tyrinėti tavo kūną"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-21',
    type: 'whisper',
    title: 'Intymumas',
    description: 'Sušnibžděk: "Man patinka, kaip tu mane lieti"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-22',
    type: 'whisper',
    title: 'Jausmingumas',
    description: 'Sušnibžděk: "Tu mane sužavėjai"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-23',
    type: 'whisper',
    title: 'Pagunda',
    description: 'Sušnibžděk: "Tavo lūpos atrodo tokios minkštos"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-24',
    type: 'whisper',
    title: 'Drąsa',
    description: 'Sušnibžděk: "Galvoju apie tave duše"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-25',
    type: 'whisper',
    title: 'Geismas',
    description: 'Sušnibžděk: "Noriu išsiaiškinti, kas tau patinka"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-26',
    type: 'whisper',
    title: 'Aistra',
    description: 'Sušnibžděk: "Tu esi nepakartojamas"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-27',
    type: 'whisper',
    title: 'Troškimas',
    description: 'Sušnibžděk: "Norėčiau pamiršti visus aplink ir bučiuoti tik tave"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-28',
    type: 'whisper',
    title: 'Gundymas',
    description: 'Sušnibžděk: "Man patinka, kai tu šypsaisi"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-29',
    type: 'whisper',
    title: 'Noras',
    description: 'Sušnibžděk: "Tu man visiškai įsirėžei į mintis"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-30',
    type: 'whisper',
    title: 'Vilionė',
    description: 'Sušnibžděk: "Man patinka tavo balsas"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-31',
    type: 'whisper',
    title: 'Fantazija',
    description: 'Sušnibžděk: "Vakar galvojau apie mus lovoje"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-32',
    type: 'whisper',
    title: 'Aistra',
    description: 'Sušnibžděk: "Norėčiau pabūti su tavimi vienatvėje"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-33',
    type: 'whisper',
    title: 'Pagunda',
    description: 'Sušnibžděk: "Tu man patinki labiau nei turėtum"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-34',
    type: 'whisper',
    title: 'Jausmingumas',
    description: 'Sušnibžděk: "Kai tu šalia, jaučiuosi kitaip"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-35',
    type: 'whisper',
    title: 'Troškimas',
    description: 'Sušnibžděk: "Man sunku susivaldyti šalia tavęs"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-36',
    type: 'whisper',
    title: 'Gundymas',
    description: 'Sušnibžděk: "Tu žinai, kaip mane sujaudinti"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-37',
    type: 'whisper',
    title: 'Drąsa',
    description: 'Sušnibžděk: "Norėčiau su tavimi išbandyti ką nors naujo"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-38',
    type: 'whisper',
    title: 'Geismas',
    description: 'Sušnibžděk: "Man patinka, kai mes liečiamės"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-39',
    type: 'whisper',
    title: 'Vilionė',
    description: 'Sušnibžděk: "Tavo akys mane hipnotizuoja"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-40',
    type: 'whisper',
    title: 'Aistra',
    description: 'Sušnibžděk: "Norėčiau būti arčiau tavęs dabar"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-41',
    type: 'whisper',
    title: 'Noras',
    description: 'Sušnibžděk: "Tu esi viskas, ko man reikia"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-42',
    type: 'whisper',
    title: 'Fantazija',
    description: 'Sušnibžděk: "Turiu planą šiai nakčiai"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-43',
    type: 'whisper',
    title: 'Pagunda',
    description: 'Sušnibžděk: "Man patinka tavo kūno forma"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-44',
    type: 'whisper',
    title: 'Troškimas',
    description: 'Sušnibžděk: "Negaliu atitraukti nuo tavęs akių"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-45',
    type: 'whisper',
    title: 'Gundymas',
    description: 'Sušnibžděk: "Tu manęs nepaleidai iš galvos"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-46',
    type: 'whisper',
    title: 'Jausmingumas',
    description: 'Sušnibžděk: "Man patinka būti su tavimi"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-47',
    type: 'whisper',
    title: 'Aistra',
    description: 'Sušnibžděk: "Tu mane įkvepi"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-48',
    type: 'whisper',
    title: 'Vilionė',
    description: 'Sušnibžděk: "Man labai patinka tavo šypsena"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-49',
    type: 'whisper',
    title: 'Drąsa',
    description: 'Sušnibžděk: "Kai tu šalia, pasaulis tampa geresnis"',
    icon: '🤫',
    color: '#FF1493',
  },
  {
    id: 'whisper-50',
    type: 'whisper',
    title: 'Geismas',
    description: 'Sušnibžděk: "Tu esi vienintelis, kurio noriu"',
    icon: '🤫',
    color: '#FF1493',
  },

  // Dare cards
  {
    id: 'dare-1',
    type: 'dare',
    title: 'Išdrįsk',
    description: 'Išdrįsk pasakyti ką nors, ko niekada nesakei',
    icon: '🔥',
    color: '#FF4500',
  },
  {
    id: 'dare-2',
    type: 'dare',
    title: 'Drąsa',
    description: 'Padaryk kažką spontaniško',
    icon: '🔥',
    color: '#FF4500',
  },
  {
    id: 'dare-3',
    type: 'dare',
    title: 'Rizika',
    description: 'Papasakok apie savo fantaziją',
    icon: '🔥',
    color: '#FF4500',
  },

  // Truth cards
  {
    id: 'truth-1',
    type: 'truth',
    title: 'Tiesa',
    description: 'Atsakyk į bet kokį partnero klausimą sąžiningai',
    icon: '💭',
    color: '#4169E1',
  },
  {
    id: 'truth-2',
    type: 'truth',
    title: 'Atvirumas',
    description: 'Papasakok kažką, ko partneris dar nežino',
    icon: '💭',
    color: '#4169E1',
  },

  // Hug cards
  {
    id: 'hug-1',
    type: 'hug',
    title: 'Apkabinimas',
    description: 'Apkabink partnerį/-ę 30 sekundžių tyloje',
    icon: '🤗',
    color: '#FFB6C1',
  },
  {
    id: 'hug-2',
    type: 'hug',
    title: 'Šiluma',
    description: 'Stipriai apkabink partnerį/-ę',
    icon: '🤗',
    color: '#FFB6C1',
  },

  // Dance cards
  {
    id: 'dance-1',
    type: 'dance',
    title: 'Šokis',
    description: 'Pašokite lėtą šokį be muzikos',
    icon: '💃',
    color: '#DA70D6',
  },
  {
    id: 'dance-2',
    type: 'dance',
    title: 'Judesys',
    description: 'Šokite kartu vieną minutę',
    icon: '💃',
    color: '#DA70D6',
  },
];

export const DEFAULT_SPICY_SETTINGS = {
  enabled: true,
  rarity: 'medium' as const, // 30% chance
  enabledTypes: [
    'kiss',
    'challenge',
    'compliment',
    'massage',
    'whisper',
    'dare',
    'truth',
    'hug',
    'dance',
  ] as const,
};

export const RARITY_LABELS = {
  rare: '🔹 Retas (5%)',
  'semi-rare': '🔸 Pusiau retas (15%)',
  medium: '⚪ Vidutinis (30%)',
  frequent: '🟡 Dažnas (40%)',
  ultra: '🔥 Ultra dažnas (50%)',
};

export const SPICY_CARD_TYPE_LABELS = {
  kiss: 'Bučinys 💋',
  challenge: 'Iššūkis 🎯',
  compliment: 'Komplimentas 💝',
  massage: 'Masažas 💆',
  slap: 'Žaismingas 👋',
  whisper: 'Šnibždesys 🤫',
  dare: 'Išdrįsk 🔥',
  truth: 'Tiesa 💭',
  hug: 'Apkabinimas 🤗',
  dance: 'Šokis 💃',
};
